project 'MiYouProject.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'MiYouProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MiYouProject

  target 'MiYouProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MiYouProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  pod 'AFNetworking','~>3.1.0'
  pod 'MLeaksFinder', '~> 0.2'
  pod 'YYKit', '~> 1.0'
  pod 'BSUIKit', '~> 1.0'
  pod 'Mantle', '~> 2.1'
  pod 'FMDB', '~> 2.6'
  pod 'SDWebImage', '~> 4.0'
  pod 'Base64nl', '~> 1.2'
  pod 'GONMarkupParser', '~> 0.7'
  pod 'Masonry', '~> 1.0'
  pod 'MJRefresh', '~> 3.1'
  pod 'MBProgressHUD', '~> 1.0'
  pod 'Bugly', '~> 2.4'
  pod 'WMPageController', '~> 2.2'
  pod 'MJExtension', '~> 3.0'
  pod 'IQKeyboardManager', '~> 4.0'
  pod 'MGSwipeTableCell', '~> 1.5'
  pod 'DZNSegmentedControl', '~> 1.3'
  pod 'ZFPlayer', '~> 2.1'
  pod 'WHCNetWorkKit', '~> 0.0'
  pod 'CustomIOSAlertView', '~> 0.9'
  pod 'VOSegmentedControl', '~> 1.0'
  pod 'UMengAnalytics', '~> 4.2'
  pod 'Bugly', '~> 2.4'
pod 'KYVedioPlayer', '~> 0.0'
  
end
