project 'MiYouProject.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'MiYouProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MiYouProject

  target 'MiYouProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MiYouProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  pod 'AFNetworking','~>3.1.0'
  pod 'MLeaksFinder', '~> 0.2'
  pod 'YYKit', '~> 1.0'
  pod 'BSUIKit', '~> 1.0'
  pod 'Masonry', '~> 1.0'
  pod 'Mantle', '~> 2.1'
  pod 'FMDB', '~> 2.6'

end
